dist: xenial
language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
matrix:
  allow_failures:
  - python: 3.5-dev
  - python: 3.6-dev
  - python: 3.7-dev
  - python: 3.8-dev
  - python: nightly
install:
- pip install -r requirements.txt
script:
- cd tests && python -m unittest discover -v
env:
  global:
    BOT_ENDPOINT: hackathon-mob.transmit.im
    BOT_TOKEN: AErVqWASwZzTXf/HOHoJ6BYjysNNM6+YgQ7Vz0OL9Shm2EnE/Qu0hnAVg14sTf2aDM4acT9ARxtv2hiHz4tOsDD4jfAlJiXVGctbpDjOZ0tVMDh/23Bx+gxN2KF+bcCnNRwdfzYb4PWfoAjtzVA4e0PuYHEbf4lI5zM9q+MJb+7GIeOFlnqwN77s2eEOby5smYtFuLp0NoJxLRKI9okuc6bE256eKkhgTs3lw6pjUUWGJQzgCdfOLjXZfIu4woezMFmbCd04KfC+Pay67U12a+Ixva7wMVtfDKMGFIBZvehz4pMowrC3ndAbbBDWUg9Y4ymxnS6cpGRhmvdn0V0MdzFhsWe/Fn/9KrnO9PljAtl8eMjAOioJoXPRQuYyspsvBssov4hjWcwZx6Xl79Bn1RGbSkCtyZQZbB/GhvPntQEkqKke9PM0nMlVJUuDdlMF1WQ78NS6Hvvi6F9wmJ8zsCRbvxNYybREBi7Fx0g2sW7fmeWo0KfqsbvblpJUsRgs7TbP4hbR2dwCjdhS8Q4RTLZS/Y6LWSBV5t9DOp+ekDBiecLHjGFrN5nfFJdOKyrP8cGaO+PlF1N3QZB//GjCdvYu1HnQQJrnY/9GrY1/6V/XErh9uz2GHYr6Kcj3To8GtpQQLu2CzceUEU7hy/tgzaKjs9+/JWDExkBP4VMV3A8=
